---
name: ARM check
on:
  workflow_dispatch:
  # run on every push on the main branch
  push:
    branches:
      - main
jobs:
  generate:
    permissions:
      contents: read

    runs-on: ubuntu-24.04-arm
    timeout-minutes: 5
    steps:
      - name: lshw
        run: sudo lshw
